import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider";
import dynamic from "next/dynamic";
const ToggleTheme = dynamic(() => import('@/components/ToggleTheme'), { ssr: false })
const Navbar = dynamic(() => import('@/components/Navbar'), { ssr: false })

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen w-screen font-sans antialiased overflow-x-hidden",
        fontSans.variable
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <div className='fixed hidden md:flex right-10 top-10 z-50'> <ToggleTheme /> </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
